name: Django Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Navigate to ApiRestPython directory
      run: |
        cd ApiRestPython

    - name: Lint code
      run: |
        python manage.py check
        python manage.py makemigrations --check --dry-run
        flake8

    - name: Run tests
      run: |
        python manage.py test
